### ISSUE TITLE
New subscription discovered on topic '/camera/depth_registered/points', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY

### ISSUE THREAD

**Issue by burf2000** [ros-drivers/openni2_camera#144]
Hello there :)

So I have just cloned: 
https://github.com/ros-drivers/openni2_camera/tree/iron

I am running Ubuntu 22.04 and Humble and I think I have the first Asus Xtion Pro Live camera

When I run
ros2 launch openni2_camera camera_with_cloud.launch.py

Launch rviz2 and select a point2 cloud subscribing to:
/camera/depth_registered/points

I get the following error:
[component_container-1] [WARN] [1732275810.491877555] [camera.points_xyzrgb]: New subscription discovered on topic '/camera/depth_registered/points', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY

**Comment by mikeferguson** [comment]
The best way to debug this is to use:

    ros2 topic info /camera/depth_registered/points -v

That will tell you (verbosely) what the QOS policies of the publisher and subscriber are. Likely, the camera pipeline is publishing as BEST_EFFORT, and RVIZ is defaulting to RELIABLE which is incompatible (but ros2 topic will give you the definite answer) - you can easily change the RVIZ subscriber settings by expanding the "Topic" section in the side bar for your point cloud subscriber.

Someday, maybe RVIZ will support auto-QOS like the CLI tools and rosbag2...

(Also, closing this since it's a config issue, not really a bug with openni2_camera)
