### ISSUE TITLE
Upgrade libopenni2 version to 2.2 on hydro

### ISSUE THREAD

**Issue by garaemon** [ros-drivers/openni2_camera#23]
Now I'm using primesense sensors and it only works on libopenni2 2.2.
I'd like to use it on hydro, so could you upgrade the version of libopenni2? 
(I don't know this repository is the correct one to request this issue)

**Comment by mikeferguson** [comment]
libopenni2 is being released from either https://github.com/jspricke/OpenNI2 or https://github.com/hcw70/OpenNI2, I'm not sure which, but I believe @jspricke did the last release.

That said, these debs are typically built on launchpad -- which means that releasing into hydro is difficult since launchpad has started to tear down build infrastructure as soon as Ubuntu releases go EOL (for instance, even with Indigo, the Saucy farm is already gone).

**Comment by garaemon** [comment]
thanks!

**Comment by jspricke** [comment]
For reference, It's now http://anonscm.debian.org/cgit/pkg-multimedia/openni2.git/. Btw. updating a library is not so easy, because we would have to be careful with ABI changes. I haven't checked it.
