### ISSUE TITLE
Call to publish() on an invalid image_transport::CameraPublisher

### ISSUE THREAD

**Issue by dgossow** [ros-drivers/openni2_camera#7]
This is what I get:

```
[ INFO] [1370658958.459688665]: Starting depth stream.
[ INFO] [1370658958.894467438]: camera calibration URL: file:///etc/robot/head_rgb.yaml
[ INFO] [1370658961.044891770]: Linear joint limits reset successfully after estop.
[FATAL] [1370658966.531155375]: ASSERTION FAILED
        file = /tmp/buildd/ros-groovy-image-transport-1.10.3-0precise-20130418-2038/src/camera_publisher.cpp
        line = 126
        cond = false
        message = 
[FATAL] [1370658966.531319404]: Call to publish() on an invalid image_transport::CameraPublisher
[FATAL] [1370658966.531372437]: 

[head_camera_nodelet_manager-1] process has died [pid 13453, exit code -5, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=head_camera_nodelet_manager __log:=/home/dgossow/.ros/log/3d0eac6e-cfc2-11e2-bf3f-00e0f426264b/head_camera_nodelet_manager-1.log].
log file: /home/dgossow/.ros/log/3d0eac6e-cfc2-11e2-bf3f-00e0f426264b/head_camera_nodelet_manager-1*.log
```

**Comment by dgossow** [comment]
This seems to happen when there are already subscribers when the openni nodelets come up.

**Comment by jonbinney** [comment]
It looks like this problem is here: https://github.com/ros-drivers/openni2_camera/blob/master/src/openni2_driver.cpp

In OpenNI2Driver::advertiseROSTopics(), the topics are advertised. Concurrently, the new frame callbacks, such as OpenNI2Driver::newDepthFrameCallback, are called.  newDepthFrameCallback does check the number of subscribers, which should keep it from publishing on an unitialized CameraPublisher, but OpenNI2Driver::newColorFrameCallback and OpenNI2Driver::newIRFrameCallback don't appear to check the number of subscribers. So it seems like they could start publishing after the device has been initialized but before the topics are advertised.

**Comment by jkammerl** [comment]
The OpenNI frame callbacks are only registered in the ROS connection callbacks. Therefore, it is not clear to me how the CameraPublisher can be uninitialized within the frame callback. Anyways, it does not harm to add ROS subscriber checks to the color and ir frame callbacks: https://github.com/jkammerl/openni2_camera/commit/4f5bdf3a5d0f5cbf069ad52cc20759795fb88429
Please check if that fix helps.

Creating a pull-request now: 
https://github.com/ros-drivers/openni2_camera/pull/8

**Comment by jonbinney** [comment]
Yeah, you're right, it seems like those callbacks wouldn't happen til after the publishers were created anyway. Well, I'll merge in your changes and we'll see if that helps.

We should probably try running the whole node in gdb to get a backtrace and see exactly which publish call is causing the problem.

**Comment by jonbinney** [comment]
@dgossow are you still seeing this problem?

**Comment by mikeferguson** [comment]
I can no longer reproduce this and the thread has gone cold -- reopen this if you can reproduce still.
